---

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
# uncomment if not using reverse proxy
#    ports:
#      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      - frontend

volumes:
  portainer_data:

networks:
  frontend:
    external: true
